export const seedRecipes = [
  {
    title: "Zucchini Zoodle Salad",
    imgUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flh3.googleusercontent.com%2FC-jw_T2pUytWahsdYxlSvC0to9PegZWKZNXA0wB0pYvoMsM8FSc_YjZPV7yTTKktJOfdq3JD-ewrvmwUEGV8sw%3Dw1200-h630-pp-rj-v1-e365&f=1&nofb=1",
    course: "Dinner",
    source: "",
    servSize: "5",
    prepMins: "25",
    prepHrs: "0",
    cookMins: "32",
    cookHrs: "0",
    ingredients: ["zucchini"],
    directions: ["zoodle it"],
    notes: "",
    id: "7ac03ab3-044f-412b-b05d-1695406ae11d",
  },
  {
    title: "Cherry Smoothie",
    imgUrl:
      "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.andersonsnutrition.com%2Fwp-content%2Fuploads%2F2019%2F07%2Fcherry-smoothie.png&f=1&nofb=1",
    course: "",
    source:
      "https://www.aspicyperspective.com/salted-caramel-chocolate-chip-cookie-bars/",
    servSize: "1",
    prepMins: "5",
    prepHrs: "0",
    cookMins: "5",
    cookHrs: "0",
    ingredients: ["cherry", "ice", "fun"],
    directions: ["drinkit"],
    notes: "",
    id: "96156345-0e65-498a-8fd4-1c0fa4a39126",
  },
  {
    title: "Funfetti Cake",
    imgUrl:
      "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fdeliciouslyyum.com%2Fwp-content%2Fuploads%2F2014%2F11%2FFrosted-Funfetti-Cake-4.jpg&f=1&nofb=1",
    course: "Dessert",
    source: "",
    servSize: "12",
    prepMins: "15",
    prepHrs: "1",
    cookMins: "45",
    cookHrs: "0",
    ingredients: ["sprinkled"],
    directions: ["add sprinkles"],
    notes: "",
    id: "328ecbd4-7934-4cb4-85df-77b667c34878",
  },
  {
    title: "Cinnamon Rolls",
    imgUrl:
      "https://tasteofartisan.com/wp-content/uploads/2020/05/Sourdough-Cinnamon-Rolls-1.jpg",
    course: "",
    source: "",
    servSize: "12",
    prepMins: "25",
    prepHrs: "2",
    cookMins: "30",
    cookHrs: "0",
    ingredients: ["cinnamon"],
    directions: ["roll"],
    notes: "",
    id: "9c64d4ee-effe-4b65-9bfe-15b965adaf61",
  },
  {
    title: "Gnocchi",
    imgUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmediterranealuxuryhouse.com%2Fblog%2F_mamawp%2Fwp-content%2Fuploads%2F2016%2F02%2FIMG_3656.jpeg&f=1&nofb=1",
    course: "Dinner",
    source: "",
    servSize: "1",
    prepMins: "5",
    prepHrs: "3",
    cookMins: "25",
    cookHrs: "4",
    ingredients: ["potatoes", "tomatoes", "cheese"],
    directions: ["bake", "eat", "chub"],
    notes: "",
    id: "4bb3b214-c44d-4aed-8c1e-aceb5664995f",
  },
  {
    title: "Apple Blondies with Caramel Glaze",
    imgUrl: "https://kitchenfunwithmy3sons.com/wp-content/uploads/2019/08/Apple-Blondies-3-700x700.jpg",
    course: "",
    source: "",
    servSize: "4",
    prepMins: "30",
    prepHrs: "0",
    cookMins: "40",
    cookHrs: "0",
    ingredients: ["nuts", "apples", "flour", "caramel"],
    directions: ["do stuff", "add and mix things", "put a nut on it"],
    notes: "",
    id: "b2f75623-d78b-4ade-aafd-aafe4e90ebb9",
  },
];
